backend:
  name: github
  repo: VrachiPop/lemza-news
  branch: main
  base_url: https://authetincationdecap.hingllima-vrachit.workers.dev
  auth_endpoint: auth

media_folder: "src/assets/images"
public_folder: "../../assets/images"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog"
    label: "Lajmet"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulli", name: "title", widget: "string"}
      - {label: "Data e Publikimit", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD HH:mm"}
      - {label: "Foto Kryesore", name: "heroImage", widget: "image", required: false}
      - {label: "Përshkrimi", name: "description", widget: "text"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["Lajme"]
      - {label: "Përmbajtja", name: "body", widget: "markdown"}
      - { label: "Thënia e Ditës (Opsionale)", name: "quoteOfTheDay", widget: "string", required: false }

local_backend: false