backend:
  name: github
  repo: VrachiPop/lemza-news
  branch: main
  base_url: https://authetincationdecap.hingllima-vrachit.workers.dev
  auth_endpoint: auth

media_folder: "src/assets/images"
public_folder: "../../assets/images"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog"
    label: "Lajmet"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulli", name: "title", widget: "string"}
      - {label: "Data e Publikimit", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD HH:mm"}
      - {label: "Foto Kryesore", name: "heroImage", widget: "image", required: false}
      - {label: "Përshkrimi", name: "description", widget: "text"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["Lajme"]
      - {label: "Përmbajtja", name: "body", widget: "markdown"}
      - { label: "Thënia e Ditës", name: "quoteOfTheDay", widget: "string", required: false }

# KOLEKSIONI PËR JSON (SINGLETONS)
  - name: "settings"
    label: "Cilësimet dhe Të dhënat"
    delete: false # Nuk lejohet fshirja e skedarëve të të dhënave
    files:
      # EDITOR'S PICKS
      - label: "Editor's Picks"
        name: "curated"
        file: "src/data/curated.json"
        fields:
          - label: "Artikujt e Zgjedhur"
            name: "picks"
            widget: "list"
            field: { label: "Slug i Artikullit", name: "item", widget: "string" }

      # HOROSKOPI
      - label: "Horoskopi"
        name: "horoscope"
        file: "src/data/horoscope.json"
        fields:
          - label: "Parashikimet"
            name: "predictions"
            widget: "list"
            fields:
              - { label: "Shenja", name: "sign", widget: "string" }
              - { label: "Teksti", name: "text", widget: "text" }

local_backend: false